claim_and_wonder/urls.py
from django.urls import include, path
from django.contrib import admin
from polls.views import landing

urlpatterns = [
    path(r'conf/', include(('conf.urls', "conf"), namespace="conf")),
    path('accounts/', include('django.contrib.auth.urls')),
    path(r'admin/', admin.site.urls),
    path(r'captcha/', include('captcha.urls')),
    path(r'polls/', include(('polls.urls', "polls"), namespace="polls")),#, "polls")),#, namespace="polls")),
    path(r'', landing),
    

]

conf/urls.py
from django.urls import path

from . import views

urlpatterns = [
	path(r'signup/', views.signup, name='signup'),

]

polls/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path(r'add_claim', views.add_claim, name="add_claim"),
    path(r'vote', views.vote, name="vote"),
    path(r'', views.poll, name="poll"),
    path(r'<int:no>', views.poll, name="poll"),
    path(r'end_of_line', views.end_of_line, name="end_of_line"),
    path(r'profile', views.user_home, name="user_home"),
    path(r'report', views.report, name="report"),
    path(r'submissions', views.submissions, name="submissions"),
    path(r'decide', views.decide, name="decide"),
]

polls/models.py
from __future__ import unicode_literals

from django.db import models
from django.contrib.auth.models import User

# Create your models here.


class Claim(models.Model):
	"""
	every claim gets its model instance
	"""	
    text = models.TextField(max_length=200, blank=False)
    time_created = models.DateTimeField(auto_now_add=True)
    right_answer = models.NullBooleanField()
    yes = models.IntegerField(default=0)
    no = models.IntegerField(default=0)
    skip = models.IntegerField(default=0)
    reported = models.IntegerField(default=0)
    blocked = models.BooleanField(default=False)
    user = models.ForeignKey(
        User, default=None, null=True, on_delete=models.CASCADE)

    def __unicode__(self):
        return self.text


class Vote(models.Model):
	"""
	This model connects claims to users 
	"""
    user = models.ForeignKey(
        User, default=None, null=True, on_delete=models.CASCADE)
    claim = models.ForeignKey(Claim, on_delete=models.CASCADE)
    vote = models.NullBooleanField()


class Report(models.Model):
	"""
	Collect reported claims and block reported claims
	"""
    user = models.ForeignKey(
        User, default=None, null=True, on_delete=models.CASCADE)
    claim = models.ForeignKey(Claim, on_delete=models.CASCADE)


class Submission(models.Model):
	"""
	Model for submissions to decided claims.
	"""
    claim = models.ForeignKey(Claim, on_delete=models.CASCADE)
    comment = models.TextField(max_length=500, blank=True)
    evidence = models.TextField(max_length=500)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    submitted_answer = models.NullBooleanField()
    status = models.BooleanField(default=True)

# #these two are to make sure that we a) automatically create a profile instance once we create a user instance and b) we can update the profile through the user. see https://simpleisbetterthancomplex.com/tutorial/2016/07/22/how-to-extend-django-user-model.html#onetoone
# @receiver(post_save, sender=User)
# def create_user_profile(sender, instance, created, **kwargs):
#     if created:
#         Profile.objects.create(user=instance)

# @receiver(post_save, sender=User)
# def save_user_profile(sender, instance, **kwargs):
#     instance.profile.save()

polls/forms.py
from polls.models import Claim
from polls.models import Submission
from django.forms import ModelForm, RadioSelect, Textarea


class ClaimForm(ModelForm):
    class Meta:
        model = Claim
        fields = ['text', 'yes', 'no']


SUBMISSION_CHOICES = (
    (0, 'Correct'),
    (1, 'False'),
)


class SubmissionForm(ModelForm):
    class Meta:
        model = Submission
        fields = ['submitted_answer', 'evidence', 'comment']
        widgets = {'submitted_answer': RadioSelect(choices=SUBMISSION_CHOICES), 'evidence': Textarea(
            attrs={'cols': 40, 'rows': 3}), 'comment': Textarea(attrs={'cols': 40, 'rows': 3})}
        labels = {
                  'evidence': "Link some external evidence here.", 'comment': "Further comments."}

polls/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
import json
from random import randint, choice

from .forms import SubmissionForm
from .models import Claim, Vote, Submission, Report
from django.conf import settings


def landing(request):

    if request.user.is_authenticated:
        return HttpResponseRedirect(reverse("polls:poll"))
    return render(request, 'polls/landing.html')

# @login_required()


def poll(request, no=None):
    # first bit is to decide which claims should come next
    possible_claims = Claim.objects.filter(
        blocked=False).filter(right_answer=None)
    sam = 0

    if request.user.is_authenticated:
        possible_claims = possible_claims.exclude(vote__user=request.user).exclude(
            report__user=request.user).order_by("pk")

    else:
        sam = randint(0, len(possible_claims) - 1)

    if len(possible_claims) != 0:
        next_claim = possible_claims[sam]
        next_url = reverse("polls:poll", args=(next_claim.id,))

    else:
        next_url = reverse("polls:end_of_line")

    if no == None:
        return HttpResponseRedirect(next_url)

    # process submissions from the menu
    if request.method == 'POST':
        claim = Claim.objects.get(pk=no)
        if "submission" in request.POST:
            submission_form = SubmissionForm(request.POST)
            if submission_form.is_valid():
                submission = submission_form.save(commit=False)
                submission.user = request.user
                submission.claim = claim
                submission.save()

        return HttpResponseRedirect(next_url)

    claim = Claim.objects.get(pk=no)
    submission_form = SubmissionForm()
    return render(request, 'polls/poll.html', {'claim': claim, 'form': submission_form, 'next_url': next_url})


def vote(request):
        # this function is called from ajax
    if request.method == 'POST':
        try:
            claim = Claim.objects.get(pk=request.POST['no'])
            answer = request.POST['answer']
            if answer == 'yes':
                claim.yes += 1

            elif answer == 'no':
                claim.no += 1

            claim.save()

            if request.user.is_authenticated:
                vote = Vote(user=request.user, claim=claim)
                if answer == "yes":
                    vote.vote = True

                elif answer == "no":
                    vote.vote = False
                vote.save()

            return HttpResponse(
                json.dumps({"yes": claim.yes, "no": claim.no}),
                content_type="application/json"
            )

        except:
            return HttpResponse(
                json.dumps({"mistake": "mistake"}),
                content_type="application/json"
            )

    else:
        return HttpResponse(
            json.dumps({"nothing to see": "this isn't happening"}),
            content_type="application/json"

        )


def add_claim(request):
        # ajax function to add a claim
    if request.method == 'POST':
        try:
            if request.user.is_authenticated:
                claim = Claim(text=request.POST['text'], user=request.user)
            else:
                claim = Claim(text=request.POST['text'], user=None)
            claim.save()
            return HttpResponse(
                json.dumps(claim.id),
                content_type="application/json"
            )

        except:
            return HttpResponse(
                json.dumps({"mistake": "mistake"}),
                content_type="application/json"
            )

    else:
        return HttpResponse(
            json.dumps({"nothing to see": "this isn't happening"}),
            content_type="application/json"

        )


def report(request):
        # ajax function to report a claim
    if request.method == 'POST':
        claim = Claim.objects.get(pk=request.POST['no'])
        claim.reported += 1
        report = Report(claim=claim)

        if claim.reported >= settings.REPORT_LIMIT:
            claim.blocked = True

        claim.save()
        report.save()
        return HttpResponse(
            json.dumps({"url": "success"}),
            content_type="application/json"
        )

    else:
        return HttpResponse(
            json.dumps({"nothing to see": "this isn't happening"}),
            content_type="application/json"
        )

# @login_required()


def end_of_line(request):
        # displayed if a user has voted on all open claims
    return render(request, 'polls/end_of_line.html')


@login_required()
def user_home(request):
        # profile page
    claims = Claim.objects.filter(
        user=request.user).order_by("time_created").reverse()
    votes = Vote.objects.filter(user=request.user).exclude(
        vote=None).order_by("pk").reverse()
    return render(request, 'polls/profile.html', {'claims': claims, 'votes': votes})


@staff_member_required
def submissions(request):
        # overview over submitted claims to decide them, restricted to editors
    submissions = Submission.objects.filter(status=True)
    return render(request, 'polls/submissions_interface.html', {'submissions': submissions})


def decide(request):
        # ajax for the decision on submissions
    if request.method == 'POST':
        print(request)
        submission = Submission.objects.get(pk=request.POST['id'])
        if request.POST['accept']:
            submission.claim.right_answer = submission.submitted_answer
            submission.claim.save()

        submission.status = False
        submission.save()

        return HttpResponse(
            json.dumps({"success": "success"}),
            content_type="application/json"
        )

    else:
        return HttpResponse(
            json.dumps({"nothing to see": "this isn't happening"}),
            content_type="application/json"
        )

templates/polls/base-logged.html
{% extends "polls/base.html" %}
{% load staticfiles %}
{% block style-base %}
{% block style %} {% endblock style %}
{% endblock %}
{% block content-base  %}
{% block content %}
  
{% endblock content %}
<a href="#" data-toggle="modal" data-target=".add"><i class="fas fa-plus"></i>
</a>
<!-- Large modal -->
<div class="modal fade bs-example-modal-lg add" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
  <div class="modal-dialog modal-lg" role="document" style="height:70vh;">
    <div class="modal-content">
      <div class="row">
        <div class="col-md-12">
          <strong>Add new claim</strong>
          <p></p>
        </div>
        <div class="col-md-12">
          <form action="" id="add_claim" method="post">
            {% csrf_token %}
            <textarea class="enterclaim" rows="10" cols="1" name="claim" wrap="soft" active></textarea>
          </div>
          <div class="col-md-12" style="height:20vh;">
            <input class="select-btn btn-lg addclaim blue" type="button" value="Add" name="save"/>
          </div>
        </form>
        
      </div>
    </div>
  </div>
</div>
</div>
{% endblock %}
{% block script-base %}
{% block script %}

{% endblock script %}

<script src="{% static 'js/add_claim.js' %}" type="text/javascript"></script>
<script src="{% static 'js/login_create_new.js' %}" type="text/javascript"></script>
{% endblock script-base %}

templates/polls/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:og="http://ogp.me/ns#" xmlns:fb="http://www.facebook.com/2008/fbml">
	<meta charset="utf-8">
	<head>
		<!-- Global site tag (gtag.js) - Google Analytics -->
		<script async src="https://www.googletagmanager.com/gtag/js?id=UA-71839611-3"></script>
		<script>
		window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments);}
		gtag('js', new Date());
		gtag('config', 'UA-71839611-3');
		</script>
		<!-- Latest compiled and minified CSS -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
		<!-- Optional theme -->
		<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
		<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
		<!-- Latest compiled and minified JavaScript -->
		<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
		<!-- <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}"> -->
		<!--<script src="https://use.fontawesome.com/43308c4fa0.js"></script>-->
		<!--<link rel="stylesheet" href="{% static 'css/fontawesome.min.css' %}">-->
		<script defer src="{% static 'fa/svg-with-js/js/fontawesome-all.js' %}"></script>
		<link href="https://fonts.googleapis.com/css?family=Raleway:400,600,800" rel="stylesheet">
		<link href="{% static 'css/claim.css' %}" rel="stylesheet">
	</head>
	{% block style-base %} {% endblock %}
	<body>
		<div class="take_care_of_browser">
			{% block content-base %} {% endblock %}
		</div>
		{% block script-base %} {% endblock %}
		<script type="text/javascript">
		var viewportHeight = $('.take_care_of_browser').innerHeight();
		$('.take_care_of_browser').css({ height: (viewportHeight + 200) });
		</script>
	</body>
</html>

templates/polls/end_of_line.html
{% extends "polls/base-logged.html" %}
{% block content %}
	<div class="row">
		<div class="main poll-text">
			Sorry, you've voted on all open claims.
		</div>
	</div>
	<a href="{% url 'polls:user_home' %}"><i class="fas fa-dot-circle"></i></a>
{% endblock content %}

templates/polls/landing.html
{% extends "polls/base.html" %}
{% block content-base %}
  <div class="landing">
    <div class="row">
      <div class="col-md-12">
        <p class="large-text"><strong> Future up!</strong></p>
      </div>
    </div>
    <div class="row scroll" style="height:60%;">
      
      <p>Futurez is what it says on the tin. Get involved with what the world might look like later today, next month, or in 100 years.</p>
      <p>Expose yourself to people's ideas about the future and create your own predictions to see what other people think about them.</p>
      <p>Futurez is <a href="https://github.com/pboes/claim_and_wonder">open-source</a> and non-profit. Try it now without signing up.</p>
    </div>
  </div>
  
  <div class="row">
    <div class="col-lg-12 col-md-12 col-sm-12">
      <button class="btn-lg red large-text" >
      <a href="{% url 'polls:poll' %}">Enter</a>
      </button>
    </div>
  </div>
  <!--  <div class="row" style="height:20%;">
    
    <div class="col-lg-6 col-md-6 col-sm-6">
      <button class="btn green large-text" >
      <a href="{% url 'conf:signup' %}">SignUp</a>
      </button>
    </div>
    <div class="col-lg-6 col-md-6 col-sm-6">
      
      <button class="btn-lg blue large-text" >
      <a href="{% url 'login' %}">Login</a>
      </button>
    </div>
  </div> -->
</div>
{% endblock %}

templates/polls/poll.html
{% extends "polls/base-logged.html" %}
{% load staticfiles %}
{% block style %}
{% endblock style %}
{% block content %}
	
	<div class="row poll-div">
		<!-- 		<form action="{% url 'polls:poll' claim.id %}" method="post">
				<input type="hidden" name="claim-id" value="{{claim.id}}">
			{% csrf_token %} -->
			
			
			<div class="col col-md-12">
				
				<div class="poll-text">{{claim.text}}</div>
			</div>
		</div>
		<!-- 		<div class="row" style="height: 20%;">
			<div class="col-xs-4 col-sm-4 col-md-4 select-col">
						<button class="select-btn btn-lg green" type="submit" name="yes"/><i class="fas fa-check fa-2x"></i></button>
			</div>
			<div class="col-xs-4 col-sm-4 col-md-4 select-col">
						<button class="select-btn btn-lg skip" type="submit" name="skip"/><i class="fas fa-chevron-right fa-2x"></i></button>
			</div>
			<div class="col-xs-4 col-sm-4 col-md-4 select-col">
						<button class="select-btn btn-lg red" type="submit" name="no"/><i class="fas fa-times fa-2x"></i></button>
			</div>
		</div>
	</form>-->
	<button type="button" class="yes"><i class="fas fa-check-circle yes-circle"></i></button>
	<button type="button" class="no"><i class="fas fa-times-circle no-circle"></i></button>
	{% if request.user.is_authenticated %}
		<a href="{% url 'polls:user_home' %}"><i class="fas fa-home"></i></a>
	{% else %}
		<a href="#" data-toggle="modal" data-target="#profilemodal"><i class="fas fa-home"></i>
		</a>
		<div class="modal fade bd-example-modal-lg" id="profilemodal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
			<div class="modal-dialog modal-lg">
				<div class="modal-content">
					<p style="font-size:3vh;">
						In order to get access to profile features, you need to log in or sign up. With a profile, you can check how others voted on your claims, review claims on which you have voted, and more. Do it, we don't ask for an email!
						
						<div class="row">
							<div class="col-md-12 col-lg-6">
								<button class="btn green large-text" >
								<a href="{% url 'conf:signup' %}">Sign up</a>
								</button>
							</div>
							<p></p>
							<div class="col-md-12 col-lg-6">
								<button class="btn blue large-text" >
								<a href="{% url 'login' %}">Login</a>
								</button>
							</div>
						</div>
					</p>
				</div>
			</div>
		</div>
	{% endif %}
	<button type="button" class="report"><i class="fas fa-exclamation"></i></button>
	<a href="#" data-toggle="modal" data-target=".submission"><i class="fas fa-lightbulb"></i>
	</a>
	<!-- Large modal -->
	<div class="modal fade bs-example-modal-lg submission" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel">
		<div class="modal-dialog modal-lg" role="document" style="height:70vh;">
			<div class="modal-content">
				<div class="row">
					<div class="col-md-12">
						<p style="font-size:3vh;">Do you think this claim has been decided? Submit the evidence here.</p>
					</div>
					<div class="col-md-12">
						<form action="{% url 'polls:poll' claim.id %}" id="add_submission" method="post">
							{% csrf_token %}
							{{ form.non_field_errors }}
							<div class="form-group">
								{{ form.submitted_answer.errors }}
								<label for="{{ form.submitted_answer.id_for_label }}">Submitted Answer:</label>
								<div class="btn-group" data-toggle="buttons">
									<label class="select-btn btn btn-secondary active green">
										<input type="radio" name="submitted_answer" id="id_submitted_answer_0" autocomplete="off" checked> Correct
									</label>
									<label class="select-btn btn btn-secondary red">
										<input type="radio" name="submitted_answer" id="id_submitted_answer_1" autocomplete="off"> False
									</label>
								</div>
							</div>
							<div class="form-group">
								{{ form.evidence.errors }}
								<label for="{{ form.evidence.id_for_label }}">Evidence:</label>
								{{ form.evidence}}
							</div>
							<div class="form-group">
								{{ form.comments.errors }}
								<label for="{{ form.comment.id_for_label }}">Comments:</label>
								{{ form.comment}}
							</div>
							<div class="col-md-12" style="height:20vh;">
								<input class="select-btn btn-lg submission blue" type="submit" value="Submit" name="submission"/>
							</div>
						</form>
						
					</div>
				</div>
			</div>
		</div>
	</div>
	<div class="modal fade bd-example-modal-lg alert-warning" id="reportmodal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
		<div class="modal-dialog modal-lg">
			<div class="modal-content">
				You have reported this claim. Once a certain number of users report a claim, it will automatically be removed. Check the guidelines for reporting for more information.
				<button class="btn-lg green large-text" >
				<a href="{% url 'polls:poll' %}">Go to next claim</a>
				</button>
			</div>
		</div>
	</div>
	<div class="modal fade bd-example-modal-lg" data-backdrop="static" id="votemodal" tabindex="-1" role="dialog" aria-labelledby="mySmallModalLabel" aria-hidden="true">
		<div class="modal-dialog modal-lg">
			<div class="modal-content">
				What others think
				<div class="ct-chart" stlye="width:100%; height:100%;"></div>
				<div id="stats"></div>
				
				<button class="btn-lg blue large-text" style="margin: 40px;">
				<a href="{{next_url}}">Next claim</a>
				</button>
			</div>
		</div>
	</div>
{% endblock content %}
{% block script %}
	<script type="text/javascript">
	jQuery(document).ready(addClickHandlers());
	function addClickHandlers() {
	jQuery('.report').on('click', function(event) {
	jQuery.ajax({
	url: "/polls/report",
	type: "POST",
	data: {"no": "{{claim.id}}",}
	}).done(
	function(task) {
	$('#reportmodal').modal('show')
	//window.location.href = task['url']
	});
	});
	jQuery('.yes').on('click', function(event) {
	jQuery.ajax({
	url: "/polls/vote",
	type: "POST",
	data: {"no": "{{claim.id}}", "answer": "yes"}
	}).done(
	function(stats) {
		var viewportHeight = $('.take_care_of_browser').innerHeight();
			var viewportWidth = $('.take_care_of_browser').innerWidth();
	new Chartist.Pie('.ct-chart', {
	series: [stats['yes'], stats['no']]
	}, {
	width:viewportWidth/2,
	height:viewportHeight/3,
	});
	$('#votemodal').modal('show')
	});
	});
	jQuery('.no').on('click', function(event) {
	jQuery.ajax({
	url: "/polls/vote",
	type: "POST",
	data: {"no": "{{claim.id}}", "answer": "no"}
	}).done(
	function(stats) {
			var viewportHeight = $('.take_care_of_browser').innerHeight();
			var viewportWidth = $('.take_care_of_browser').innerWidth();
	new Chartist.Pie('.ct-chart', {
	series: [stats['yes'], stats['no']]
	}, {
	width:viewportWidth/2,
	height:viewportHeight/3,
	});
	$('#votemodal').modal('show')
	});
	});
	}
	</script>
	<link rel="stylesheet" href="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.css">
	<script src="//cdn.jsdelivr.net/chartist.js/latest/chartist.min.js"></script>
	
	<script>
	</script>
{% endblock script %}

templates/polls/polls_home.html
{% extends "polls/base.html" %}
{% block content %}
	<div class="row">
		<div class="col-md-12 section_title">
			
			<h1>Latest claims</h1>
		</div>
	</div>
	{% for claim in claims %}
		
		<div class="row overview_row">
			<div class="col-xs-2 col-sm-2 col-md-2 green" >
				{{claim.yes}}
			</div>
			<a href="{% url 'polls:poll' claim.id %}">
				<div class="col-xs-8 col-sm-8 col-md-8">
					{{claim.text}}
					
				</div>
			</a>
			<div class="col-xs-2 col-sm-2 col-md-2 red">
				{{claim.no}}
			</div>
		</div>
	{% endfor %}
{% endblock content %}

templates/polls/submissions_interface.html
{% extends "polls/base.html" %}
{% load staticfiles %}
{% block style-base %}
    <style>
        html {
    position: relative;
    overflow: hidden;
    height: 100%;
    }
    * {
    margin: 0;
    padding: 0;
    }
    </style>
{% endblock %}
{% block content-base %}
    <div class="tab-pane">
        <a href="{% url 'polls:user_home' %}"><i class="fas fa-home"></i></a>
        {% for submission in submissions %}
            
            <div class="row" id="submission-{{forloop.counter}}">
                
                <div class="col-xs-12 col-sm-12 col-md-12">
                    
                    
                    <p><strong>Claim:</strong>{{submission.claim.text}}</p>
                    <p><strong>Subm. Answer:</strong>
                        {% if submission.submitted_answer %}
                            
                            Correct
                        {% else %}
                            False
                        {% endif %}
                    </p>
                    <p><strong>Evidence:</strong>{{submission.evidence}}</p>
                    <p><strong>Comments:</strong>{{submission.comment}}</p>
                    <div class="row" style="height: 20vh;">
                        <div class="col-xs-6 col-sm-6 col-md-6 select-col">
                            <input class="select-btn btn-lg green" id="accept-{{forloop.counter}}" type="button" value="Accept" name="accept"/>
                        </div>
                        <div class="col-xs-6 col-sm-6 col-md-6 select-col">
                            <input class="select-btn btn-lg red" id="reject-{{forloop.counter}}"type="button" value="Reject" name="reject"/>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}
{% block script-base %}
    <script type="text/javascript">
    jQuery(document).ready(addClickHandlers());
    function addClickHandlers() {
    {% for submission in submissions %}
        
        jQuery('#accept-{{forloop.counter}}').on('click', function(event) {
        jQuery.ajax({
        url: "/polls/decide",
        type: "POST",
        data: {"id": "{{submission.id}}", "accept": true }
        }).done(
        function(task) {
        jQuery('#submission-{{forloop.counter}}').hide();
        });
        });
        jQuery('#reject-{{forloop.counter}}').on('click', function(event) {
        jQuery.ajax({
        url: "/polls/decide",
        type: "POST",
        data: {"id": "{{submission.id}}", "accept": false }
        }).done(
        function(task) {
        jQuery('#submission-{{forloop.counter}}').hide();
        });
        });
    {% endfor %}
    }
    // This code is a snippet that makes sure the csrf token is somehow passed from the initial view to the ajaxview, since these cannot be passed on by the jquery...
    $(function() {
    // This function gets cookie with a given name
    function getCookie(name) {
    var cookieValue = null;
    if (document.cookie && document.cookie != '') {
    var cookies = document.cookie.split(';');
    for (var i = 0; i < cookies.length; i++) {
    var cookie = jQuery.trim(cookies[i]);
    // Does this cookie string begin with the name we want?
    if (cookie.substring(0, name.length + 1) == (name + '=')) {
    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
    break;
    }
    }
    }
    return cookieValue;
    }
    var csrftoken = getCookie('csrftoken');
    /*
    The functions below will create a header with csrftoken
    */
    function csrfSafeMethod(method) {
    // these HTTP methods do not require CSRF protection
    return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
    }
    function sameOrigin(url) {
    // test that a given url is a same-origin URL
    // url could be relative or scheme relative or absolute
    var host = document.location.host; // host + port
    var protocol = document.location.protocol;
    var sr_origin = '//' + host;
    var origin = protocol + sr_origin;
    // Allow absolute or scheme relative URLs to same origin
    return (url == origin || url.slice(0, origin.length + 1) == origin + '/') ||
    (url == sr_origin || url.slice(0, sr_origin.length + 1) == sr_origin + '/') ||
    // or any other URL that isn't scheme relative or absolute i.e relative.
    !(/^(\/\/|http:|https:).*/.test(url));
    }
    $.ajaxSetup({
    beforeSend: function(xhr, settings) {
    if (!csrfSafeMethod(settings.type) && sameOrigin(settings.url)) {
    // Send the token to same-origin, relative URLs only.
    // Send the token only if the method warrants CSRF protection
    // Using the CSRFToken value acquired earlier
    xhr.setRequestHeader("X-CSRFToken", csrftoken);
    }
    }
    });
    });
    </script>
    
{% endblock %}